- name: collecting logs 
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: create a file
      ansible.builtin.command: touch /tmp/sagar.txt

    - name: collect logs
      ansible.builtin.shell: cat /var/log/messages >> /tmp/sagar.txt

    #- name: installing package
     # ansible.builtin.package: 
      # name: java
      # state: present

    - name: installing package
      ansible.builtin.package: 
       name: java
       state: absent
      