- name: collecting logs 
  hosts: local
  connection: local
  tasks:
    - name: create a file
      ansible.builtin.command: touch /tmp/sagar.txt

    - name: collect logs
      ansible.builtin.command: cat /var/log/messages >> /tmp/sagar.txt

      
      
      