- name: EC2 instance creation
  hosts: local
  connection: localhost
  tasks:
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: "public-compute-instance"
      vpc_subnet_id: subnet-0376be834be6f3982
      instance_type: t3.micro
      security_group: sg-0e5594f3e1a035cf3
      image_id: ami-09c813fb71547fc4f
      count: 1
    
