- name: nginx install and run
  hosts: web
  become: yes
  tasks: 
   - name: nginx install
     ansible.builtin.package:
       name: java
       state: present
   
   - name: run nginx and enable
     ansible.builtin.service:
       name: nginx
       state: started
       enabled: yes
